config/routes.rb
Rails.application.routes.draw do
  get "/admin" => "sessions#new"
  resources :posts, param: :slug
  resource :session
  resource :registration, only: %i[new create]
  resources :passwords, param: :token

  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/post.rb
class Post < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  has_rich_text :content
  validates :title, presence: true, length: { minimum: 5 }
  validates :content, presence: true, length: { minimum: 10 }
  belongs_to :user
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
require "net/http"
require "json"
require "open-uri"

class User < ApplicationRecord
  has_secure_password
  has_one_attached :avatar
  has_many :sessions, dependent: :destroy
  has_many :posts, dependent: :destroy

  normalizes :email_address, with: ->(e) { e.strip.downcase }

  before_save :attach_avatar_from_github

  def attach_avatar_from_github
    return unless github_username.present?

    url = "https://api.github.com/users/#{github_username}"
    uri = URI(url)
    response = Net::HTTP.get(uri)
    user_data = JSON.parse(response)

    if user_data["avatar_url"]
      self.avatar.attach(io: URI.open(user_data["avatar_url"]), filename: "#{github_username}_avatar.jpg")
    end
  rescue StandardError => e
    Rails.logger.error("Erro ao buscar avatar do GitHub: #{e.message}")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: { ie: false }

  def current_user
    @current_user ||= Current.user
  end
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :require_authentication
    helper_method :authenticated?
  end

  class_methods do
    def allow_unauthenticated_access(**options)
      skip_before_action :require_authentication, **options
    end
  end

  private
    def authenticated?
      resume_session
    end

    def require_authentication
      resume_session || request_authentication
    end

    def resume_session
      Current.session ||= find_session_by_cookie
    end

    def find_session_by_cookie
      Session.find_by(id: cookies.signed[:session_id]) if cookies.signed[:session_id]
    end

    def request_authentication
      session[:return_to_after_authenticating] = request.url
      redirect_to new_session_path
    end

    def after_authentication_url
      session.delete(:return_to_after_authenticating) || root_url
    end

    def start_new_session_for(user)
      user.sessions.create!(user_agent: request.user_agent, ip_address: request.remote_ip).tap do |session|
        Current.session = session
        cookies.signed.permanent[:session_id] = { value: session.id, httponly: true, same_site: :lax }
      end
    end

    def terminate_session
      Current.session.destroy
      cookies.delete(:session_id)
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  allow_unauthenticated_access
  before_action :set_user_by_token, only: %i[ edit update ]

  def new
  end

  def create
    if user = User.find_by(email_address: params[:email_address])
      PasswordsMailer.reset(user).deliver_later
    end

    redirect_to new_session_path, notice: "Password reset instructions sent (if user with that email address exists)."
  end

  def edit
  end

  def update
    if @user.update(params.permit(:password, :password_confirmation))
      redirect_to new_session_path, notice: "Password has been reset."
    else
      redirect_to edit_password_path(params[:token]), alert: "Passwords did not match."
    end
  end

  private
    def set_user_by_token
      @user = User.find_by_password_reset_token!(params[:token])
    rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to new_password_path, alert: "Password reset link is invalid or has expired."
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  allow_unauthenticated_access only: %i[ index show ]
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :set_user, only: %i[ create new edit update ]

  # GET /posts or /posts.json
  def index
    @posts = Post.where(draft: false).order(created_at: :desc)
    @drafts = Post.where(draft: true).order(created_at: :desc)
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = @user
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_path, status: :see_other, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      # temporarily use aceitando a pesquisa por nome do draft
      @post = Post.friendly.find(params[:slug])
    end

    def set_user
      @user = current_user
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content, :spotify_track_url, :draft)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  allow_unauthenticated_access only: %i[ new create ]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_session_url, alert: "Try again later." }

  def new
  end

  def create
    if user = User.authenticate_by(params.permit(:email_address, :password))
      start_new_session_for user
      redirect_to after_authentication_url
    else
      redirect_to new_session_path, alert: "Try another email address or password."
    end
  end

  def destroy
    terminate_session
    redirect_to root_path, notice: "See you later!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update ]

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: "User was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :avatar)
  end

  def set_user
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KernelPanic | <%= content_for(:title) || "Posts" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">

    <meta name="description" content="KernelPanic é um blog semanal sobre tecnologia, programação e desenvolvimento de software, vida e reflexões.">
    <meta name="keywords" content="tecnologia, programação, desenvolvimento de software, vida, reflexões, blog">
    <meta name="author" content="Lucas Borges">
    <meta name="distribution" content="Rio Grande do Sul, Brazil">


    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <nav class="bg-[#14161a] text-white p-5">
        <div class="container mx-auto flex justify-center items-center">
          <div class="flex flex-col items-center">
            <a href="/" class="font-bold text-2xl">
              <%= image_tag 'logo_branca.svg', class: 'h-10 md:h-12 glow' %>
            </a>
            <span class="font-extrabold text-xs flex items-center mt-1 justify-center">KernelPanic</span>
          </div>
        </div>
      </nav>
    </header>
    <main class="container mx-auto px-5 flex items-center justify-center">
    
      <%= yield %>

      <% if authenticated? %>
      <div class="fixed bottom-5 right-5">
        <div class="flex items-center justify-center">

          <script>
            function alterMenu(){
              const menu = document.querySelector('#admin-menu')
              if(menu.classList.contains('hidden')){
                menu.classList.remove('hidden')
              } else {
                menu.classList.add('hidden')
              }
            }
          </script>

          <button id="admin-btn" class="bg-[#FFFF] text-black p-3 rounded-full shadow-lg" onclick="alterMenu()">
            <span class="flex justify-center items-center font-bold" ><%= image_tag 'logo.svg', class: 'h-8 w-8' %></span>
          </button>
          <ul id="admin-menu" class="hidden absolute w-[150px] right-0 bottom-14 bg-white shadow-lg rounded-lg flex flex-col gap-2 p-2 ">
            <li class="text-white bg-[#2d2d2d] p-2 rounded-lg w-full">
              <%= link_to 'Novo Post', new_post_path, class: "font-bold text-sm cursor-pointer w-full" %>
            </li>
            <li class="text-white bg-[#2d2d2d] p-2 rounded-lg w-full">
              <%= button_to 'Sair', session_path, method: :delete, data: { turbo_method: :delete }, class: "font-bold cursor-pointer text-sm w-full text-left" %>
            </li>
          </ul>
          

        </div>
      </div>

      <% end %>
    </main>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, class: "contents") do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul class="list-disc ml-6">
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mt-5">
    <%= form.label :title, "Titulo", class: "block font-medium" %>
    <%= form.text_field :title, class: "rounded-md px-3.5 py-2.5 w-full border border-gray-200" %>
  </div>

  <div class="mt-5">
    <%= form.label :spotify_track_url, "Spotify embed link", class: "block font-medium" %>
    <%= form.text_field :spotify_track_url, class: "rounded-md px-3.5 py-2.5 w-full border border-gray-200" %>
  </div>

  <div class="mt-5 flex gap-1">
    <%= form.check_box :draft %> <%= form.label :draft, "Rascunho", class: "block font-medium " %>
  </div>

  <div class="mt-5">
    <%= form.label :content, "Conteúdo", class: "block font-medium" %>
    <%= form.rich_text_area :content, class: "rounded-md px-3.5 py-2.5 w-full border border-gray-200" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-md px-3.5 py-2.5 bg-green-600 hover:bg-green-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>" class="my-10 mb-24 space-y-5 mx-auto post-content">
  <div class="flex md:mx-10 flex-col border-b-2 border-[#2d2d2d] md:flex-row">    
    <div class="flex gap-3 mb-5">
      <% if post.user.avatar.attached? %>
        <%= image_tag post.user.avatar, class: "rounded-full w-12 sm:w-20" %>
      <% end %>
      <div class="flex flex-col justify-center ">
        <span class="font-bold text-xl"><%= post.user.name %></span>
        <span class="text-gray-500"><%= time_ago_in_words(post.created_at).capitalize %> atrás</span>
      </div>
    </div> 
  </div>
  <div class="md:px-10 bg-[#14161a] text-lg sm:text-xl border-b-2 pb-5 border-[#2d2d2d]">
    <h2 class="font-extrabold text-left md:text-left text-3xl md:text-4xl py-2 mb-5 pl-3 border-l-8 border-[#2d2d2d] "><%= link_to post.title, post_path(post) %></h2>
    <div class="text-justify px-3">
      <%= @post.content %>
    </div>
  </div>
  <% if @post.spotify_track_url? %>
    <div class="flex flex-col gap-3 mx-auto bg-[#121418] rounded-xl p-5 w-full md:w-4/5 lg:w-2/3">
      <h3 class="text-center text-xl md:text-3xl font-bold" > Ouça no mesmo tema </h3>
      <iframe style="border-radius:12px" src=<%= @post.spotify_track_url %> width="100%" height="152" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"
      class="mx-auto"
      ></iframe>
    </div>
  <%end%>

</div>

app/views/posts/edit.html.erb
<% content_for :title, "Editando post" %>

<div class="md:w-2/3 w-full mx-auto mt-5 p-10">
  <h1 class="font-bold text-4xl">Editando post</h1>

  <%= render "form", post: @post %>

  <%= link_to "Mostrar o post", @post, class: "mt-5 ml-2 rounded-md px-3.5 py-2.5 bg-stone-800 hover:bg-stone-700 inline-block font-medium" %>
  <%= link_to "Voltar", posts_path, class: "mt-5 ml-2 rounded-md px-3.5 py-2.5 bg-stone-800 hover:bg-stone-700 inline-block font-medium" %>
</div>

app/views/posts/index.html.erb
<% content_for :title, "Posts" %>

<div class="w-full py-24">
  <% if notice.present? %>
    <p class="mx-auto py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div id="posts" class="max-w-fit mx-auto">
    <% if @posts.any? %>
      <% @posts.each do |post| %>
        <div class="w-full flex mx-auto mb-10 text-2xl border-l-8 border-[#4a0bae96] post">
          <div class="ml-5 flex flex-col items-start justify-center gap-1 w-full">
            <%= link_to truncate(post.title, length: 50), post_path(post), class: "text-2xl md:text-4xl font-bold hover:font-bolder w-full" %>
            <div class="flex items-center h-5 gap-0.5"> 
              <% if post.user.avatar.attached? %>
                <%= image_tag post.user.avatar, class: "rounded-full w-4 sm:w-4" %>
              <% end %>
              <span class="text-[#ffff]/60 text-xs"><%= post.user.name %>,</span>
              <span class="text-[#ffff]/60 text-xs"><%= time_ago_in_words(post.created_at) %> atrás</span>
            </div>
          </div>
        </div>
                   
      <% end %>
    <% else %>
      <p class="text-center my-10">Nenhum post no momento.</p>
    <% end %>
  </div>

<% if authenticated? %>
  <div class="flex items-center justify-center w-3/5 mx-auto my-10">
    <hr class="w-2/5 mx-auto text-stone-700">
    <h2 class="text-3xl mx-8 font-bold">Rascunhos</h2>
    <hr class="w-2/5 mx-auto text-stone-700">
  </div>
  <div id="drafts" class="max-w-fit mx-auto">
    <% if @drafts.any? %>
      <% @drafts.each do |draft| %>
        <div class="w-full flex mx-auto text-2xl my-10 border-l-8 border-[#ffffff96]">
          <div class="ml-5 flex flex-col items-start justify-center gap-1 w-full">
            <%= link_to truncate(draft.title, length: 50), post_path(draft), class: "text-2xl md:text-4xl font-bold hover:font-bolder w-full" %>
            <div class="flex items-center h-5 gap-0.5"> 
              <% if draft.user.avatar.attached? %>
                <%= image_tag draft.user.avatar, class: "rounded-full w-4 sm:w-4" %>
              <% end %>
              <span class="text-[#ffff]/60 text-xs"><%= draft.user.name %>,</span>
              <span class="text-[#ffff]/60 text-xs"><%= time_ago_in_words(draft.created_at) %> atrás</span>
            </div>
          </div>
        </div>
                   
      <% end %>
    <% end %>
  </div>
<% end %>
</div>

app/views/posts/new.html.erb
<% content_for :title, "Novo Post" %>

<div class="md:w-2/3 w-full mx-auto mt-5 p-10">
  <h1 class="font-bold text-4xl">Novo Post</h1>

  <%= render "form", post: @post %>

  <%= link_to "Voltar", posts_path, class: "mt-5 ml-2 rounded-md px-3.5 py-2.5 bg-stone-800 hover:bg-stone-700 inline-block font-medium" %>
</div>

app/views/posts/show.html.erb
<% content_for :title, @post.title %>

<div class=" md:w-2/3 w-full mx-auto">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center flex-row-reverse">
    <% if authenticated? && Current.user == @post.user %>
      <%= link_to "Editar", edit_post_path(@post), class: "mt-2 rounded-md px-3.5 py-2.5 bg-stone-800 hover:bg-stone-700 inline-block font-bold" %>
      <div class="inline-block ml-2">
        <%= button_to "Apagar", @post, method: :delete, class: "mt-2 rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-bold cursor-pointer", data: { turbo_confirm: "Tem certeza?" } %>
      </div>
    <% end %>
  </div>
  <%= render @post %>
</div>